# Generated by Django 6.1.1 on 2026-10-01 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPieza',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de pieza',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('rol', models.CharField(choices=[('vendedor', 'Vendedor'), ('administrador', 'Administrador')], max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id_pieza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('condicion', models.CharField(choices=[('nueva', 'Nueva'), ('reacondicionada', 'Reacondicionada')], max_length=20)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piezas', to='inventario.categoriapieza')),
            ],
            options={
                'verbose_name_plural': 'Piezas',
            },
        ),
        migrations.CreateModel(
            name='LoteCompra',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_compra', models.DateField(auto_now_add=True)),
                ('id_pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.pieza')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.cliente')),
                ('id_vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='inventario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='inventario.pieza')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.venta')),
            ],
        ),
    ]
